name: CI/CD portfolio webserver

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio-webserver:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/portfolio-webserver:latest ${{ secrets.DOCKER_USERNAME }}/portfolio-webserver:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-webserver:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-webserver:${{ github.sha }}

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_PRIVATE_KEY}}
          script: |
            # remove stopped containers and dangling images
            docker container prune -f && docker image prune -af
            
            # stop and remove existing container if running
            docker stop portfolio-webserver 
            docker rm portfolio-webserver
            
            # remove docker image
            docker rmi densoftdev/portfolio-webserver:latest
            
            # docker pull image
            docker pull ${{ secrets.DOCKER_USERNAME }}/portfolio-webserver:latest
            
            # run docker container
            docker run --name portfolio-webserver -d --network projectsnet -p 80:80 -p 443:443 ${{ secrets.DOCKER_USERNAME }}/portfolio-webserver:latest
          
